### ISSUE TITLE
Only toggling between single and double quotes (JavaScript/React Native)

### ISSUE THREAD

**Issue by pranavchary** [twifty/atom-switch-quotes#2]
OS: MacOS Catalina (10.15.3)
Atom version: 1.45.0 x64
Package version: 0.2.0
Language: JavaScript (ES6) with React Native library

Mac users don't have an alt key, but toggling between single and double quotes works for me using ctrl-' or option-' shortcuts. Wondering if this is what's causing the issue or if there's something else in there

**Comment by twifty** [comment]
Let's try ruling out a key mapping issue first. Place the cursor within a string and try running the commands `switch-quotes:cycle` and `switch-quotes:toggle`. The first should change between single and double quotes, the second should change between all string types.

**Comment by pranavchary** [comment]
Running ``switch-quotes:cycle`` on double quotes gave me single quotes. Running it again on the single quotes gave me a template string, and running it a number of times after that kept me stuck on the template string.

Running ``switch:quotes:toggle`` on double quotes gave me a template string, where it got stuck again no matter how many times I ran it after that.

So I was at least able to get to the template string quotes this time, just looks like it's not behaving the way you explained it should.

**Comment by twifty** [comment]
It sound like a language problem to me. Which plugin do you have installed for the syntax highlighting?

To fix this, I need to add scope rules for the language in question.

**Comment by pranavchary** [comment]
> Which plugin do you have installed for the syntax highlighting?
Sorry, I'm not too sure what you meant by this. I'm fairly new to using Atom. I only know that I have a plugin that highlights every instance of a word when I select it, but that's about it.

I tried disabling that and running the same commands again, but no change in output.

**Comment by twifty** [comment]
> Sorry, I'm not too sure what you meant by this.
Atom uses a different plugin for each language (C, C++, JAVA, es6...) that you write in the editor. If you look in the bottom right of the window, you should see the name of the language. Hover over it and it will say something like "File is using XXX grammar".

There are two plugins, that I know of, for React. One is called `react` the other is `nuclide`. There may be others. I need to know which you are using so that I can install it and find the problem.

**Comment by pranavchary** [comment]
When I hover over the language it just says "File is using JavaScript grammer".  So I suppose it's using whatever the default syntax highlighter is for Atom. Would that be Tree-sitter?

**Comment by twifty** [comment]
> Would that be Tree-sitter?

Tree-Sitter is a parser, but most modern grammars use the Tree-Sitter to parse the file, then build a syntax, which atom uses to color the display. `switch-quotes` uses that syntax to detect the strings.

Can you run `apm list --installed --enabled` from the command line. This will list the plugins installed in atom. While the key bindings may need tweaking for Mac, I can't think of anything that would stop the package from working other than one of your plugins.

**Comment by pranavchary** [comment]
Here's a list of all the results:

- atom-beautify@0.33.4
- atom-live-server@2.3.0
- auto-update-packages@1.0.1
- autoclose-html@0.23.0
- autocomplete-modules@2.3.0
- bracket-colorizer@1.4.0
-busy-signal@2.0.1
-double-brackets-with-spaces@2.1.0
-es6-javascript@1.0.0
-file-icons@2.1.39
-highlight-selected@0.17.0
-intentions@1.1.5
-linter@2.3.1
-linter-eslint@8.5.5
-linter-ui-default@1.8.1
-minimap@4.29.9
-pigments@0.40.2
-platformio-ide-terminal@2.10.0
-react-rnative-snippets@0.1.1
-switch-quotes@0.2.0
-tree-view-copy-relative-path@1.2.0

**Comment by twifty** [comment]
None of those packages look like they would modify the editor in any problematic way. I don't have access to a Mac, so this is very difficult to reproduce.

If you are feeling brave, you could edit the source code to enable debugging. Other than that, it'll have to wait until I have time to setup a VM and install Mac.

**Comment by pranavchary** [comment]
Sure, I can look into it and see what might be causing the issue. If I figure anything out I'll make sure to let you know!

**Comment by twifty** [comment]
The constructor of the `QuoteSwitcher` class has a `this.debug` flag. Setting it to true will log messages to the console.

**Comment by pranavchary** [comment]
Hey, just an update: I haven't had a chance to take a deep dive into this yet, but while editing some other JavaScript (non-React) code, I noticed that the toggling and cycling was working perfectly for me. So I guess the problem lies specifically when writing React or JSX code in a .js file. I'll look into it more this tomorrow, most likely.

**Comment by twifty** [comment]
If you can provide me with a sample .jsx file containing all possible string types for React/JSX, that will allow me to do some testing.

**Comment by pranavchary** [comment]
Haven't been experiencing this issue lately, closing this for now.
